name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch


jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - run: dotnet test Terraform.NET.slnx --configuration Release

      - run: dotnet pack Terraform.NET.slnx --configuration Release --no-build --output artifacts/packages

      - name: publish packages
        run: dotnet nuget push "artifacts/packages/*.nupkg" --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
