<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <Version>1.0.0-preview.2</Version>
    <PackageId>Terraform.NET.PowerPlatform</PackageId>
    <PackageDescription>Power Platform provider extensions for Terraform.NET.</PackageDescription>
    <Authors>Adam Coulter</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RootNamespace>TF.PowerPlatform</RootNamespace>
    <AssemblyName>TF.PowerPlatform</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../TF/TF.csproj" />
  </ItemGroup>

</Project>
